### ISSUE TITLE
Allow embedding prediction markets

### ISSUE THREAD

**Issue by LamaMansour** [gnosis/pm-trading-ui#525]
**As a partner of Olympia and prediction markets platform, I would like to be able to embed markets offered on Olympia in my own website, so that my website viewers can easily view and access Olympia markets**

**Acceptance Criteria**
- Allow individual markets to be embedded

**Comment by andre-meyer** [comment]
@LamaMansour do we need a new view on the MarketDetail Page to display the code that needs to be embedded or do we want to communicate this differently for now?

**Comment by LamaMansour** [comment]
@andre-meyer Your idea of a share button is good for this. Thanks
